### DISCUSSION TITLE
CSS Variables

### DISCUSSION THREAD

**Discussion by kylenathan** [goods/ember-assembly#33] [General]
# Breaking change!

This release moves theming from build time based variables to CSS variables so that theming in consuming apps becomes much easier, and can be fine tuned through setting CSS variables with selectors (as opposed to having to select exposed classes).

E.g.

* Old approach
```css
.nav-bar :global(.ui-button) {
    background: blue;
}
```

* New approach
```css
.nav-bar {
    --ea-colour-button-background: blue;
}
```

### Migrating from <0.13

To migrate, existing apps will need to move their theme config from `environment.js` to `app.css` / `app.scss` and set the values for the `:root` selector.

E.g.
```css
:root {
    --ea-colour-blue-b0: #0000ff;
}
```

<hr /><em>This discussion was created from the release <a href='https://github.com/goods/ember-assembly/releases/tag/v0.13.0'>CSS Variables</a>.</em>
